version: "2"

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
    - whitespace
  settings:
    revive:
      rules:
        - name: var-naming
          disabled: true

formatters:
  enable:
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
